# -*- coding: utf-8 -*-
"""
Sav tekst sajta, na tri jezika.

Pravila koja vaze za svaku recenicu ovde:

  1. Naslov prodaje razlog dolaska, ne opisuje prostor. Ne "trpezarija za
     pedeset" nego sta gost time dobija.
  2. Uz svaki podatak ide i zasto je gostu bitan. Broj bez posledice je prazan.
  3. Bez dugih crta. Recenica se prelama tackom ili zarezom.
  4. Bez praznih fraza: dobrodosli, oaza, savrseno mesto, nezaboravno.

Posle izmene pokrenuti:  python _build/generate.py
"""

# ============================================================== SRPSKI

SR = {
    "code": "sr",
    "htmllang": "sr-Latn-RS",
    "ime": "Srpski",
    "nav": {
        "pocetna": "Početna", "kuce": "Kuće", "kuca2": "Dvosobna kuća",
        "kuca1": "Jednosobna kuća", "restoran": "Restoran",
        "imanje": "Imanje", "apartmani": "Apartmani",
        "bazen": "Bazen", "galerija": "Galerija", "proslave": "Proslave",
        "trpeza": "Trpeza", "fruska": "Fruška gora", "kontakt": "Kontakt",
    },
    "c": {
        "mesto": "Vrdnik · Fruška gora",
        "upit": "Pošaljite upit",
        "pozovite": "Pozovite nas",
        "poziv_natpis": "Rezervacija",
        "sve_slike": "Pogledajte galeriju",
        "nazad": "Nazad na imanje",
        "preskoci": "Pređite na sadržaj",
        "meni": "Meni",
        "jezik": "Jezik",
        "prava": "Sva prava zadržana.",
        "izrada": "Dizajn i izrada",
        "pratite": "Pratite nas",
        "poseta": "U poseti",
        "kuca": "Kuća",
        "ponuda": "Ponuda",
        "okolina": "Okolina",
        "poziv_h": "Proverite da li je vaš datum slobodan",
        "poziv_p": "Pošaljite datum i broj gostiju. Javljamo se istog dana, sa svim što treba da znate pre nego što se odlučite.",
    },
    "home": {
        "title": "Ilkićev kućerak · privatno imanje u Vrdniku na Fruškoj gori",
        "desc": "Smeštaj u obnovljenoj sremskoj kući u Vrdniku, restoran sa domaćom hranom i bazen sa slanom vodom. Izdaje se celo imanje i samo jednom društvu, na 40 minuta od Novog Sada.",
        "h1": ["Prenoćište, kuhinja", "i vinski podrum", "na jednom mestu"],
        "uvod": "Smeštaj u obnovljenoj sremskoj kući, restoran sa domaćom hranom i bazen sa slanom vodom. U Vrdniku, na 40 minuta od Novog Sada. Idealno za porodični odmor, vikend u dvoje ili miran boravak u prirodi Fruške gore.",
        "stubovi": [
            ("apartmani", "Boravak", "Ostanite dan ili tri. Bez recepcije, bez hodnika i bez suseda iza zida."),
            ("proslave", "Proslave", "Krštenje, rođendan ili svadba u užem krugu, u prostoru koji tog dana ne delite ni sa kim."),
            ("trpeza", "Trpeza", "Domaća kuhinja koja se dogovara prema tome ko dolazi i šta voli."),
        ],
        "odlike": [
            ("sapa", "Pet friendly", "Pas putuje sa vama, ne ostaje kod nekog drugog"),
            ("kapija", "Potpuna privatnost", "Tog dana kroz kapiju ulazi samo vaše društvo"),
            ("put", "40 minuta od Novog Sada", "Dovoljno blizu za dolazak i povratak istog dana"),
            ("vrt", "Vrt od 900 m²", "Mesta za decu, roštilj i dugačak sto u hladu"),
            ("parking", "Besplatan parking", "Ispred kapije, dovoljno za celo društvo"),
        ],
        "ukratko_natpis": "Ukratko",
        "ukratko_h": "Stara sremska kuća iz 19. veka, sa celim imanjem uz nju",
        "ukratko_p1": "Kućerak je obnovljena sremska kuća u centru Vrdnika, sa zidanom peći, drvenim gredama i vinskim podrumom ispod. Izdaje se celo imanje i samo jednom društvu.",
        "ukratko_p2": "Napolju vas čeka prostrano dvorište, orah koji pravi hlad nad bazenom i roštilj koji radi kad god zatreba.",
        "ukratko_p3": "Ocena na Google-u je 4,7 od 5, iz više od 300 utisaka.",
        "kuca_natpis": "Privatnost",
        "kuca_h": "Jedini gosti tog dana ste vi",
        "kuca_p1": "Kućerak se ne deli. Dvorište, bazen, trpezarija i podrum tog dana pripadaju samo vama. Ne smetate nikome, niko vama ne smeta i ne morate da se prilagođavate ničemu.",
        "restoran_natpis": "Restoran",
        "restoran_h": "Jelovnik po vašem izboru",
        "restoran_p": "Gosti biraju jelovnik u dogovoru sa nama, tako da sve bude prilagođeno vama.",
        "dvoriste_natpis": "Dvorište",
        "dvoriste_h": "Ceo dan stane u trideset koraka",
        "dvoriste_p": "Od kapije do trave, bazena i trpezarije pod ciglenim svodom. Sve je toliko blizu da se društvo ne razilazi i niko ne mora nikuda da se vozi.",
        "ponuda_natpis": "Zbog čega ljudi dolaze",
        "ponuda_h": "Tri razloga koja čujemo najčešće",
        "ponuda": [
            ("apartmani", "Da se isključe na dan ili dva",
             "Dva apartmana, sedamdeset kvadrata u većem, dve spavaće sobe i kamin. Dođete u petak uveče i ne morate nigde do nedelje.",
             "interior-apartment"),
            ("proslave", "Da proslave među svojima",
             "Pedeset mesta za stolom, dvorište za ceremoniju i bazen za decu. Sve na jednom mestu, pa se društvo ne seli i veče se ne prekida.",
             "celebrations-tall"),
            ("trpeza", "Da svi sednu za isti sto",
             "Kuvamo za vaše društvo, ne po kartici. Recite ko dolazi i šta voli, a sto vas čeka pun u dogovoreno vreme.",
             "table-setting"),
        ],
        "bazen_natpis": "Voda",
        "bazen_h": "Kupanje i kad je napolju hladno",
        "bazen_p": "Vrdnik je banjsko mesto i ovamo se dolazi zbog vode i vazduha, ne samo leti. Naš bazen u dvorištu je grejan i sa slanom vodom, pa se u njemu ostaje duže i kada sezona prođe. Kaskada je na jednom kraju, ležaljke u hladu, a tog dana ga koristi samo vaše društvo.",
        "utisci_natpis": "Utisci",
        "citat": "Domaćin i njegova supruga su izuzetno ljubazni. Dočekali su nas kafom i domaćim sokom.",
        "citat_izvor": "Gost · Google, 4,7 od 5 (više od 300 ocena)",
        "fruska_natpis": "Okolina",
        "fruska_h": "Priroda vam je na pragu, a ne na sat vožnje",
        "fruska_p": "Vrdnik je poslednje naselje pre nacionalnog parka, pa staza kreće čim izađete iz dvorišta. Jutarnja šetnja bez planiranja, manastiri i vinarije posle doručka, i povratak na ručak. Do Novog Sada dvadeset tri kilometra, do Beograda sedamdeset, pa vikend prođe bez dugih vožnji.",
        "fruska_cta": "Šta se obilazi iz Vrdnika",
    },
    "kuce": {
        "title": "Kuće · Ilkićev kućerak, Vrdnik",
        "desc": "Dve kuće u istom dvorištu u Vrdniku. Dvosobna sa dve spavaće sobe i jednosobna sa dva kreveta, obe sa svojom kuhinjom i kupatilom.",
        "h1": "Kuće",
        "uvod": "Dve kuće u istom dvorištu. Uzimaju se zajedno kada dolazi veće društvo, ili svaka za sebe.",
        "izbor_h": "Dve kuće, jedno dvorište",
        "k2_h": "Dvosobna kuća",
        "k2_p": "Dve spavaće sobe, bračni krevet u jednoj i dva kreveta u drugoj, sa sopstvenim kupatilom i potpuno opremljenom kuhinjom.",
        "k1_h": "Jednosobna kuća",
        "k1_p": "Mesto od dva kreveta, uz koje ide potpuno opremljena kuhinja i kupatilo.",
        "napomena_h": "Zajedno ili svaka za sebe",
        "napomena_p": "Imanje se izdaje jednom društvu, pa dvorište, bazen i podrum ostaju vaši u oba slučaja. Recite koliko vas je i naći ćemo raspored.",
    },

    "kuca1": {
        "title": "Jednosobna kuća · Ilkićev kućerak, Vrdnik",
        "desc": "Jednosobna kuća u Vrdniku sa dva kreveta, potpuno opremljenom kuhinjom i kupatilom.",
        "h1": "Jednosobna kuća",
        "uvod": "Za dvoje koji ostaju da prespavaju, sa svojom kuhinjom i kupatilom.",
        "natpis": "Smeštaj",
        "a_h": "Dva kreveta, kuhinja i kupatilo",
        "a_p1": "Mesto od dva kreveta, uz koje ide potpuno opremljena kuhinja i kupatilo.",
        "a_p2": "Uzima se sama kada dolazite udvoje, ili uz dvosobnu kuću kada je društvo veće. Bazen, trpezarija i podrum su vam na raspolaganju isto kao i gostima iz dvosobne.",
        "oznake": ["2 kreveta", "Opremljena kuhinja", "Kupatilo"],
        "napomena_h": "Za veće grupe",
        "napomena_p": "Obe kuće se uzimaju zajedno, pa cela porodica spava na istom mestu. Recite koliko vas je i naći ćemo raspored.",
    },

    "kuca2": {
        "title": "Dvosobna kuća · Ilkićev kućerak, Vrdnik",
        "desc": "Dvosobna kuća u Vrdniku: dve spavaće sobe, potpuno opremljena kuhinja i sopstveno kupatilo.",
        "h1": "Dvosobna kuća",
        "uvod": "Za goste koji ostaju da prespavaju, sa sopstvenom kuhinjom i kupatilom.",
        "natpis": "Smeštaj",
        "a_h": "Dve sobe, kuhinja i kupatilo samo za vas",
        "a_p1": "Dve spavaće sobe, bračni krevet u jednoj i dva kreveta u drugoj. Kuća poseduje kupatilo i potpuno opremljenu kuhinju.",
        "a_p2": "Nema recepcije ni fiksnih termina, dolazak i odlazak dogovaramo prema vašem putu.",
        "oznake": ["2 spavaće sobe", "Bračni + 2 kreveta", "Opremljena kuhinja", "Kupatilo"],
        "napomena_h": "Za veće grupe",
        "napomena_p": "Kada dolazi veće društvo, izdaje se cela kuća, pa svi spavaju na istom mestu. Recite koliko vas je i naći ćemo raspored.",
    },
    "restoran": {
        "title": "Restoran · domaća sremačka kuhinja, Vrdnik",
        "desc": "Restoran pod ciglenim svodom sa pedeset mesta, domaćom sremačkom kuhinjom i vinskim podrumom ispod kuće.",
        "h1": "Restoran",
        "uvod": "Kuva se za društvo, ne po kartici. Šta će biti na stolu dogovaramo pre nego što dođete.",
        "natpis": "Trpeza",
        "sala_h": "Pedeset mesta pod ciglenim svodom",
        "sala_p1": "Cela familija sedne za jedan sto umesto da se deli po sobama, a kiša ne može da pokvari dan. Sto se postavlja i napolju, u dvorištu, kada je vreme za to.",
        "sala_p2": "Kuhinja je sremačka i domaća, bez pretenzija. Namirnice su odavde, a količine takve da niko ne ustaje gladan. Ako neko ne jede meso ili ne sme gluten, recite unapred i to se reši.",
        "podrum_h": "Vinski podrum ispod kuće",
        "podrum_p": "Degustacija ne mora nigde da se vozi. Fruška gora je vinorodna, vinarije su na nekoliko minuta, a nekoliko njih radi u samom Vrdniku.",
        "radno_h": "Radno vreme",
        "radno_p": "Otvoreno svakog dana. Za grupe i proslave kuhinja radi po dogovoru, pa nas pozovite pre dolaska da vam sto bude spreman.",
    },
    "imanje": {
        "title": "Imanje · Ilkićev kućerak, Vrdnik",
        "desc": "Šta dobijate kada rezervišete kućerak: kuću sa dva apartmana, dvorište sa grejanim bazenom, salu sa pedeset mesta i vinski podrum, sve za jedno društvo.",
        "h1": "Imanje",
        "uvod": "Sve što vam treba za dan ili vikend nalazi se u istom dvorištu, pa nema selidbe, vožnje ni dogovaranja sa trećima.",
        "natpis": "Imanje",
        "sta_h": "Šta dobijate kada rezervišete",
        "redovi": [
            ("Kuća", "Sremačka prizemnica sa drvenim gredama i ciglenim svodovima. Dovoljno velika za celo društvo, dovoljno mala da se svi čuju."),
            ("Apartmani", "Dva apartmana za one koji ostaju da prespavaju, pa niko ne mora da traži smeštaj u okolini niti da vozi kući posle večere."),
            ("Sala i trpezarija", "Pedeset mesta pod ciglenim svodom. Cela familija sedne za jedan sto umesto da se deli po sobama, a kiša ne može da pokvari dan."),
            ("Podrum", "Vinski podrum ispod kuće, za degustaciju ili za onaj deo večeri kada se društvo prirodno podeli."),
            ("Bazen", "Grejan i sa slanom vodom, sa kaskadom i ležaljkama. Deca imaju gde da provedu dan, a odrasli ne moraju da ih voze na kupanje."),
            ("Dvorište", "Trava, lavanda i ruže, roštilj i prostor za binu i dekoraciju, pa ceremonija i slavlje mogu napolju."),
            ("Parking", "Ispred kapije i besplatan, pa niko ne kruži po selu tražeći mesto."),
        ],
        "detalji_h": "Dobro je znati pre nego što rezervišete",
        "detalji": [
            ("Kućni ljubimci", "Ne primamo ih. Žao nam je, ali je tako."),
            ("Deca", "Dobrodošla u svakom uzrastu. Bazen nema ogradu, pa računajte na to ako dovodite najmlađe."),
            ("Dolazak i odlazak", "Nemamo recepciju ni fiksne termine. Dogovaramo se prema vašem putu, pa ne morate da jurite sat."),
            ("Wi‑Fi i parking", "Wi‑Fi je besplatan u celom dvorištu, parking ispred kapije."),
            ("Plaćanje", "Dogovaramo pri rezervaciji, bez naknadnih stavki."),
        ],
    },
    "apartmani": {
        "title": "Apartmani · Ilkićev kućerak, Vrdnik",
        "desc": "Dva apartmana u kućerku u Vrdniku, za goste koji ostaju da prespavaju. Bez recepcije, bez hodnika i bez suseda iza zida.",
        "h1": "Apartmani",
        "uvod": "Za one koji ne žele da voze kući posle večere ili hoće da produže vikend.",
        "a1_h": "Veći apartman",
        "a1_p": "Sedamdeset kvadrata i dve spavaće sobe, bračni krevet u jednoj i dva kreveta u drugoj. Ima svoju kuhinju i kupatilo, pa ne zavisite ni od koga, a kamin i terasa okrenuta ka gori su razlog da ostanete i kada zahladni.",
        "a1_oznake": ["70 m²", "2 spavaće sobe", "Bračni + 2 kreveta", "Kuhinja", "Kamin", "Terasa", "Pogled na goru", "Klima"],
        "a2_h": "Manji apartman",
        "a2_p": "Za dvoje, u istoj kući i istom dvorištu. Bazen, trpezarija i podrum ostaju vam na raspolaganju isto kao i gostima iz većeg apartmana.",
        "a2_oznake": ["Za dvoje", "Kupatilo", "Klima", "Izlaz u dvorište", "Bazen"],
        "napomena": "Za veće grupe izdaje se cela kuća, pa cela familija spava na istom mestu. Recite koliko vas je i naći ćemo raspored.",
    },
    "bazen": {
        "title": "Bazen · Ilkićev kućerak, Vrdnik",
        "desc": "Bazen u dvorištu kućerka u Vrdniku, sa hidromasažnom kadom, grejanjem i slanom vodom.",
        "h1": "Bazen",
        "uvod": "Bazen sa hidromasažnom kadom, grejanjem i slanom vodom po vašem izboru.",
        "voda_h": "Grejana ili slana voda, po vašem izboru",
        "voda_p1": "Bazen sa hidromasažnom kadom, grejanjem i slanom vodom po vašem izboru.",
        "voda_p2": "Naš bazen je grejan i sa slanom vodom. Slana voda manje nagriza oči i kožu od hlora, pa deca u njoj izdrže duže, a sezona kupanja traje osetno duže nego kod običnog bazena. Kaskada je na jednom kraju, ležaljke u hladu.",
        "oznake": ["Hidromasažna kada", "Grejanje", "Slana voda"],
        "noc_h": "Veče ne mora da se prekida",
        "noc_p": "Uveče se upale svetla u vodi i pod svodovima i dvorište radi do kasno. Unaokolo je zid, pa nema komšije zbog koga biste morali da stišate muziku.",
    },
    "galerija": {
        "title": "Galerija · Ilkićev kućerak, Vrdnik",
        "desc": "Kako izgleda kućerak u Vrdniku: dvorište danju i noću, bazen, svodovi, apartmani i postavljeni stolovi.",
        "h1": "Galerija",
        "uvod": "Da vidite gde dolazite pre nego što se odlučite.",
    },
    "proslave": {
        "title": "Proslave · privatno dvorište i sala, Vrdnik",
        "desc": "Privatan prostor za proslave u Vrdniku. Pedeset mesta za stolom, dvorište, bazen i sala pod svodom, sve za jedno društvo i bez ograničenja u satu.",
        "h1": "Proslave",
        "uvod": "",
        "sta_h": "Šta se ovde slavi",
        "dogovor_p": "Dogovore sklapamo preko telefona i izlazimo u susret za sve navedene vrste proslava.",
        "sta": [
            ("Krštenja i slave", "Porodični ručak pod svodovima ili napolju. Kuhinja se dogovara unapred, pa domaćin provede dan za stolom, a ne u kuhinji."),
            ("Rođendani", "Od dečjih, gde deca imaju travu i bazen, do okruglih, gde se sedne za dugačak sto i ostane do kasno."),
            ("Matursko veče", "Stolovi, stolice, dekoracija i bazen na jednom mestu, pa nema selidbe u drugi lokal usred noći."),
            ("Svadbe u užem krugu", "Do pedeset zvanica, ceremonija u dvorištu i slikanje bez izlaska iz kapije."),
            ("Firme i timovi", "Tim‑bilding i godišnjice daleko od kancelarije, a opet na sat vremena od Beograda."),
        ],
        "kako_h": "Kako to izgleda u praksi",
        "kako": [
            ("Prostor", "Trava i popločana terasa napolju, sala pod ciglenim svodom ako padne kiša. Ne morate da birate unapred ni da imate rezervni plan."),
            ("Sto", "Do pedeset mesta. Okrugli stolovi, beli stolnjaci i bele stolice su naši, pa ih ne iznajmljujete posebno."),
            ("Dekoracija", "Radimo sa dekoraterima iz okoline, a primamo i vašeg. Luk od balona, cveće i rasveta prolaze kroz kapiju bez problema."),
            ("Muzika", "Bina i razglas se postavljaju u dvorištu. Zid unaokolo znači da niko ne kuca u zid u jedanaest."),
            ("Parking", "Besplatan, ispred kapije, dovoljno za celo društvo."),
        ],
        "napomena_h": "Termin",
        "napomena_p": "Vikendi u sezoni odu rano, a neki se zauzmu i godinu dana unapred. Pošaljite datum i broj gostiju i odgovaramo istog dana da li je slobodno.",
    },
    "trpeza": {
        "title": "Trpeza i podrum · domaća sremačka kuhinja, Vrdnik",
        "desc": "Domaća kuhinja koja se dogovara unapred, prema broju gostiju i prilici, uz vinski podrum ispod kuće.",
        "h1": "Trpeza",
        "uvod": "Ne birate sa kartice i ne čekate da se sve iznese. Dogovorimo se pre nego što dođete, pa sto bude spreman kad vi sednete.",
        "kuhinja_h": "Kuhinja",
        "kuhinja_p": "Sremačka i domaća, bez pretenzija. Namirnice su odavde, a količine takve da niko ne ustaje gladan. Ako neko ne jede meso ili ne sme gluten, recite unapred i to se reši bez posebne priče za stolom.",
        "jela": [
            ("Fruškogorski fruštuk", "Jutarnji sto za goste koji prespavaju. Jaja, domaći sir, kajmak, slanina, hleb i kajsijev sok, da se dan ne počinje vožnjom do pekare."),
            ("Supa i čorba", "Domaća, skuvana tog jutra za taj dan."),
            ("Sa roštilja", "Meso se peče u dvorištu, uz priloge i salate iz bašte, pa miris ide kroz celu avliju."),
            ("Kolači", "Domaći, za kraj. I za poneti, ako ostane."),
        ],
        "jela_napomena": "Meni sastavljamo prema broju gostiju i prilici. Recite koga dovodite i šta voli, ostalo je na nama.",
        "podrum_h": "Podrum",
        "podrum_p": "Ispod kuće je vinski podrum, pa degustacija ne mora nigde da se vozi. Fruška gora je vinorodna, vinarije su na nekoliko minuta, a nekoliko njih radi u samom Vrdniku.",
        "radno_h": "Radno vreme",
        "radno_p": "Otvoreno svakog dana. Za grupe i proslave kuhinja radi po dogovoru, pa nas pozovite pre dolaska da vam sto bude spreman.",
    },
    "fruska": {
        "title": "Fruška gora i Vrdnik · šta se obilazi iz kućerka",
        "desc": "Nacionalni park, osamnaest manastira, vinarije i termalna banja, sve na nekoliko minuta od kućerka u Vrdniku.",
        "h1": "Fruška gora",
        "uvod": "Vrdnik je poslednje naselje pre nacionalnog parka, pa vam je priroda na pragu, a ne na sat vožnje.",
        "natpis": "Okolina",
        "mesta_h": "Nadohvat ruke",
        "mesta": [
            ("Nacionalni park Fruška gora", "Bukove i lipove šume, obeležene staze i vidikovci. Ulaz je odmah iznad naselja, pa se u šumu stiže peške za desetak minuta."),
            ("Manastiri", "Osamnaest ih je na gori, osam u iriškoj opštini. Staro i Novo Hopovo, Velika i Mala Remeta, Ravanica, Grgeteg, Jazak i Krušedol, svi u krugu od pola sata vožnje."),
            ("Vinarije", "Fruškogorski vinski put. Nekoliko vinarija radi u samom Vrdniku, na par minuta hoda, pa degustacija ne mora da se planira kao izlet."),
            ("Vrdnička kula", "Ostaci srednjovekovnog utvrđenja iznad naselja. Uspon je kratak, a pogled ide preko celog Srema."),
            ("Banja Vrdnik", "Termalni izvor od trideset dva stepena i bazeni, u samom mestu."),
            ("Biciklom i pešice", "Staze kreću iz Vrdnika. Bicikle i jahanje organizujemo na zahtev, pa ne morate ništa da dovozite."),
        ],
        "put_h": "Koliko se putuje",
        "put": [
            ("Novi Sad", "23 km"),
            ("Beograd", "70 km"),
            ("Ruma", "15 km"),
            ("Aerodrom Nikola Tesla", "52 km"),
        ],
        "put_p": "Iz Beograda se stiže za sat vremena, iz Novog Sada za dvadesetak minuta. Zato ovde dolaze i oni koji ostaju samo na ručak, i oni koji prespavaju ceo vikend.",
    },
    "kontakt": {
        "title": "Kontakt i rezervacije · Ilkićev kućerak, Vrdnik",
        "desc": "Proverite da li je vaš datum slobodan. Telefon +381 65 288 0781, Mirka Laćarca 9, Vrdnik.",
        "h1": "Kontakt",
        "uvod": "Najbrže je telefonom, javlja se neko od nas, ne centrala. Ako vam je lakše pismeno, popunite obrazac i odgovorimo istog dana.",
        "forma_h": "Pošaljite upit",
        "forma_p": "Recite datum, koliko vas je i povod. Odgovorimo da li je slobodno i šta možemo da spremimo, pa se ostalo dogovori u razgovoru.",
        "polja": {
            "ime": "Ime i prezime", "email": "E‑pošta", "telefon": "Telefon",
            "povod": "Povod", "datum": "Datum", "gosti": "Broj gostiju",
            "poruka": "Poruka",
            "povod_opcije": ["Boravak u apartmanu", "Proslava", "Ručak ili večera", "Nešto drugo"],
            "poruka_ph": "Šta planirate, koliko vas je i šta vam je važno?",
            "posalji": "Pošaljite upit",
        },
        "poruke": {
            "obavezno": "Ovo polje je obavezno.",
            "nevalidno": "Proverite unos.",
            "salje": "Šalje se…",
            "posalji": "Pošaljite upit",
            "uspeh": "Hvala, upit je stigao. Javljamo se istog dana.",
            "neuspeh": "Slanje nije uspelo. Pozovite +381 65 288 0781 ili pišite na ilkic@kucerak-u-sremu.rs.",
        },
        "podaci_h": "Podaci",
        "adresa_l": "Adresa", "telefon_l": "Telefon", "epasta_l": "E‑pošta",
        "radno_l": "Radno vreme", "radno_v": "Svakog dana",
        "mapa_l": "Otvorite u Google mapama",
    },
}

# ============================================================== ENGLISH

EN = {
    "code": "en",
    "htmllang": "en",
    "ime": "English",
    "nav": {
        "pocetna": "Home", "kuce": "Houses", "kuca2": "Two-bedroom house",
        "kuca1": "One-bedroom house", "restoran": "Restaurant",
        "imanje": "The estate", "apartmani": "Apartments",
        "bazen": "The pool", "galerija": "Gallery", "proslave": "Celebrations",
        "trpeza": "The table", "fruska": "Fruška gora", "kontakt": "Contact",
    },
    "c": {
        "mesto": "Vrdnik · Fruška gora",
        "upit": "Send an enquiry",
        "pozovite": "Call us",
        "poziv_natpis": "Booking",
        "sve_slike": "See the gallery",
        "nazad": "Back to the estate",
        "preskoci": "Skip to content",
        "meni": "Menu",
        "jezik": "Language",
        "prava": "All rights reserved.",
        "izrada": "Design and build",
        "pratite": "Follow",
        "poseta": "Visiting",
        "kuca": "The house",
        "ponuda": "What we offer",
        "okolina": "Around us",
        "poziv_h": "Find out whether your date is free",
        "poziv_p": "Send us a date and a number of guests. We answer the same day, with everything you need before you decide.",
    },
    "home": {
        "title": "Ilkićev kućerak · a private estate in Vrdnik, Fruška gora",
        "desc": "Rooms in a restored Srem house in Vrdnik, a restaurant serving home cooking and a saltwater pool. The whole estate is let to one company at a time, forty minutes from Novi Sad.",
        "h1": ["A bed, a kitchen", "and a wine cellar", "in one place"],
        "uvod": "Rooms in a restored Srem house, a restaurant serving home cooking and a saltwater pool. In Vrdnik, forty minutes from Novi Sad. For a family holiday, a weekend for two or a quiet stay in the hills of Fruška gora.",
        "stubovi": [
            ("apartmani", "Stay", "Stay a night or three. No reception, no corridor, nobody on the other side of the wall."),
            ("proslave", "Celebrate", "A christening, a birthday or a small wedding, in a place you share with nobody that day."),
            ("trpeza", "Eat", "Home cooking put together around who is coming and what they like."),
        ],
        "odlike": [
            ("sapa", "Pet friendly", "The dog travels with you, no sitter to arrange"),
            ("kapija", "Complete privacy", "That day only your party comes through the gate"),
            ("put", "40 minutes from Novi Sad", "Close enough to come and go on the same day"),
            ("vrt", "A 900 m² garden", "Room for the children, the grill and a long table"),
            ("parking", "Free parking", "In front of the gate, enough for the whole party"),
        ],
        "ukratko_natpis": "In short",
        "ukratko_h": "A nineteenth century Srem house, with the whole estate around it",
        "ukratko_p1": "The kućerak is a restored Srem house in the middle of Vrdnik, with a masonry stove, wooden beams and a wine cellar underneath. The whole estate is let, and to one company at a time.",
        "ukratko_p2": "Outside there is a wide courtyard, a walnut tree that shades the pool and a grill that runs whenever you need it.",
        "ukratko_p3": "The rating on Google is 4.7 out of 5, from more than 300 reviews.",
        "kuca_natpis": "Privacy",
        "kuca_h": "You are the only guests that day",
        "kuca_p1": "The kućerak is not shared. That day the courtyard, the pool, the dining room and the cellar belong to you alone. You are in nobody's way, nobody is in yours, and there is nothing you have to fit around.",
        "restoran_natpis": "Restaurant",
        "restoran_h": "The menu is yours to choose",
        "restoran_p": "Guests choose the menu together with us, so that everything is set up around you.",
        "dvoriste_natpis": "The courtyard",
        "dvoriste_h": "The whole day fits inside thirty paces",
        "dvoriste_p": "From the gate to the grass, the pool and the dining room under its brick vault. Everything sits close enough that the party never splits up and nobody has to drive anywhere.",
        "ponuda_natpis": "Why people come",
        "ponuda_h": "The three reasons we hear most",
        "ponuda": [
            ("apartmani", "To switch off for a day or two",
             "Two apartments, seventy square metres in the larger one, two bedrooms and a fireplace. Arrive on Friday evening and you need not go anywhere until Sunday.",
             "interior-apartment"),
            ("proslave", "To celebrate among their own",
             "Fifty seats at the table, a courtyard for the ceremony and a pool for the children. All in one place, so the party never moves and the evening never breaks.",
             "celebrations-tall"),
            ("trpeza", "To put everyone at one table",
             "We cook for your company, not off a card. Tell us who is coming and what they like, and the table is waiting, laid, at the hour you asked for.",
             "table-setting"),
        ],
        "bazen_natpis": "Water",
        "bazen_h": "Swimming even when it is cold out",
        "bazen_p": "Vrdnik is a spa village and people come here for the water and the air, not only in summer. Our courtyard pool is heated and filled with saltwater, so it stays usable long after the season ends. A cascade at one end, loungers in the shade, and that day it belongs to your company.",
        "utisci_natpis": "Guests",
        "citat": "The host and his wife are so friendly. We had coffee and natural made juice for a welcome.",
        "citat_izvor": "A guest · Google, 4.7 out of 5 (more than 300 ratings)",
        "fruska_natpis": "Around us",
        "fruska_h": "Nature on the doorstep, not an hour down the road",
        "fruska_p": "Vrdnik is the last village before the national park, so the trail starts the moment you leave the courtyard. A morning walk that needs no planning, monasteries and wineries after breakfast, and back in time for lunch. Novi Sad is twenty-three kilometres away and Belgrade seventy, so the weekend passes without long drives.",
        "fruska_cta": "What to see from Vrdnik",
    },
    # PROVISIONAL: awaiting the client's copy.
    "kuce": {
        "title": "Houses · Ilkićev kućerak, Vrdnik",
        "desc": "Two houses in one courtyard in Vrdnik. A two bedroom house and a one bedroom house with two beds, each with its own kitchen and bathroom.",
        "h1": "Houses",
        "uvod": "Two houses in the same courtyard. Taken together when the party is larger, or each on its own.",
        "izbor_h": "Two houses, one courtyard",
        "k2_h": "Two-bedroom house",
        "k2_p": "Two bedrooms, a double bed in one and two single beds in the other, with a bathroom of its own and a fully equipped kitchen.",
        "k1_h": "One-bedroom house",
        "k1_p": "A room with two beds, and with it a fully equipped kitchen and a bathroom.",
        "napomena_h": "Together or each on its own",
        "napomena_p": "The estate is let to one company at a time, so the courtyard, the pool and the cellar are yours either way. Tell us how many of you there are and we will find the arrangement.",
    },

    "kuca1": {
        "title": "One-bedroom house · Ilkićev kućerak, Vrdnik",
        "desc": "A one bedroom house in Vrdnik with two beds, a fully equipped kitchen and a bathroom.",
        "h1": "One-bedroom house",
        "uvod": "For two who stay the night, with a kitchen and a bathroom of their own.",
        "natpis": "Accommodation",
        "a_h": "Two beds, a kitchen and a bathroom",
        "a_p1": "A room with two beds, and with it a fully equipped kitchen and a bathroom.",
        "a_p2": "Taken on its own when the two of you come, or alongside the two-bedroom house when the party is larger. The pool, the dining room and the cellar are as much yours as they are the larger house's.",
        "oznake": ["2 beds", "Equipped kitchen", "Bathroom"],
        "napomena_h": "For larger groups",
        "napomena_p": "Both houses are taken together, so the whole family sleeps in one place. Tell us how many of you there are and we will find the arrangement.",
    },

    "kuca2": {
        "title": "Two-bedroom house · Ilkićev kućerak, Vrdnik",
        "desc": "A two bedroom house in Vrdnik: two bedrooms, a fully equipped kitchen and a bathroom of its own.",
        "h1": "Two-bedroom house",
        "uvod": "For guests who stay over, with a kitchen and a bathroom of their own.",
        "natpis": "Staying",
        "a_h": "Two rooms, a kitchen and a bathroom of your own",
        "a_p1": "Two bedrooms, a double bed in one and two single beds in the other. The house has its own bathroom and a fully equipped kitchen.",
        "a_p2": "There is no reception desk and no fixed hours, arrival and departure are arranged around your journey.",
        "oznake": ["2 bedrooms", "Double + 2 beds", "Equipped kitchen", "Bathroom"],
        "napomena_h": "For larger groups",
        "napomena_p": "When a bigger party comes, the whole house goes together so everyone sleeps in one place. Tell us how many you are and we will find the arrangement.",
    },
    "restoran": {
        "title": "Restaurant · Srem home cooking, Vrdnik",
        "desc": "A restaurant under a brick vault seating fifty, with Srem home cooking and a wine cellar beneath the house.",
        "h1": "Restaurant",
        "uvod": "We cook for a company, not off a card. What goes on the table is agreed before you arrive.",
        "natpis": "The table",
        "sala_h": "Fifty seats under a brick vault",
        "sala_p1": "The whole family sits at one table instead of splitting across rooms, and rain cannot spoil the day. The table is also laid outside, in the courtyard, when the weather allows.",
        "sala_p2": "The kitchen is Srem cooking, domestic, no airs. The ingredients come from here and the quantities are such that nobody leaves hungry. If someone does not eat meat or cannot have gluten, say so in advance and it is handled.",
        "podrum_h": "A wine cellar under the house",
        "podrum_p": "A tasting means walking downstairs rather than driving anywhere. Fruška gora is wine country, the wineries are minutes away and several are in Vrdnik itself.",
        "radno_h": "Opening",
        "radno_p": "Open every day. For groups and celebrations the kitchen works by arrangement, so call before you come and your table will be ready.",
    },
    "imanje": {
        "title": "The estate · Ilkićev kućerak, Vrdnik",
        "desc": "What you get when you book: a house with two apartments, a courtyard with a heated pool, a hall seating fifty and a wine cellar, all for one company.",
        "h1": "The estate",
        "uvod": "Everything a day or a weekend needs sits in the same courtyard, so there is nothing to move between, nothing to drive to and nobody else to arrange it with.",
        "natpis": "The estate",
        "sta_h": "What you get when you book",
        "redovi": [
            ("The house", "A single-storey Srem house with timber beams and brick vaults. Big enough for the whole company, small enough that everyone can hear each other."),
            ("Apartments", "Two apartments for those who stay over, so nobody has to find a bed nearby or drive home after dinner."),
            ("Hall and dining room", "Fifty seats under a brick vault. The whole family sits at one table instead of splitting across rooms, and rain cannot spoil the day."),
            ("Cellar", "A wine cellar under the house, for a tasting or for the part of the evening when the party naturally divides."),
            ("Pool", "Heated, saltwater, with a cascade and loungers. The children have somewhere to spend the day and nobody has to drive them to a beach."),
            ("Courtyard", "Grass, lavender and roses, a grill and room for a stage and decoration, so the ceremony and the party can be outdoors."),
            ("Parking", "In front of the gate and free, so nobody circles the village looking for a space."),
        ],
        "detalji_h": "Worth knowing before you book",
        "detalji": [
            ("Pets", "We cannot take them. Sorry, but that is how it is."),
            ("Children", "Welcome at any age. The pool is not fenced, so bear that in mind with the youngest."),
            ("Arrival and departure", "No reception and no fixed times. We arrange it around your journey, so nobody is watching a clock."),
            ("Wi‑Fi and parking", "Wi‑Fi is free across the whole courtyard, parking is in front of the gate."),
            ("Payment", "Agreed when you book, with nothing added later."),
        ],
    },
    "apartmani": {
        "title": "Apartments · Ilkićev kućerak, Vrdnik",
        "desc": "Two apartments at the kućerak in Vrdnik, for guests who stay over. No reception, no corridor, nobody behind the wall.",
        "h1": "Apartments",
        "uvod": "For anyone who would rather not drive home after dinner, or who wants the weekend to run longer.",
        "a1_h": "The larger apartment",
        "a1_p": "Seventy square metres and two bedrooms, a double in one and two beds in the other. It has its own kitchen and bathroom, so you depend on nobody, and the fireplace and the terrace facing the hills are the reason people stay once it turns cold.",
        "a1_oznake": ["70 m²", "2 bedrooms", "Double + 2 beds", "Kitchen", "Fireplace", "Terrace", "Hill view", "Air conditioning"],
        "a2_h": "The smaller apartment",
        "a2_p": "For two, in the same house and the same courtyard. The pool, the dining room and the cellar are as much yours as they are the larger apartment's.",
        "a2_oznake": ["For two", "Bathroom", "Air conditioning", "Courtyard access", "Pool"],
        "napomena": "For larger groups the whole house goes together, so the whole family sleeps in one place. Tell us how many you are and we will find the arrangement.",
    },
    "bazen": {
        "title": "The pool · Ilkićev kućerak, Vrdnik",
        "desc": "The pool in the courtyard in Vrdnik, with a whirlpool tub, heating and salt water.",
        "h1": "The pool",
        "uvod": "A pool with a whirlpool tub, heating and salt water, whichever you prefer.",
        "voda_h": "Heated or salted, whichever you prefer",
        "voda_p1": "A pool with a whirlpool tub, heating and salt water, whichever you prefer.",
        "voda_p2": "Our pool is heated and filled with saltwater. Salt is gentler on eyes and skin than chlorine, so children last far longer in it and the swimming season runs noticeably longer than at an ordinary pool. A cascade at one end, loungers in the shade.",
        "oznake": ["Whirlpool tub", "Heating", "Salt water"],
        "noc_h": "The evening does not have to stop",
        "noc_p": "In the evening the lights come on in the water and under the arches and the courtyard runs late. A wall runs all the way round, so there is no neighbour to turn the music down for.",
    },
    "galerija": {
        "title": "Gallery · Ilkićev kućerak, Vrdnik",
        "desc": "What the kućerak in Vrdnik actually looks like: the courtyard by day and by night, the pool, the arches, the apartments and a table laid for guests.",
        "h1": "Gallery",
        "uvod": "So you can see where you are coming before you decide.",
    },
    "proslave": {
        "title": "Celebrations · a private courtyard and hall in Vrdnik",
        "desc": "A private venue for celebrations in Vrdnik. Fifty seats at the table, a courtyard, a pool and a vaulted hall, all for one company and with no closing hour to work around.",
        "h1": "Celebrations",
        "uvod": "",
        "sta_h": "What gets celebrated here",
        "dogovor_p": "Arrangements are made over the phone, and we take on every kind of celebration listed here.",
        "sta": [
            ("Christenings and slavas", "A family lunch under the arches or out in the courtyard. The kitchen is agreed in advance, so the host spends the day at the table rather than in it."),
            ("Birthdays", "From children's parties, where they have the grass and the pool, to round-number ones with a long table and music until late."),
            ("Prom nights", "Tables, chairs, decoration and a pool in one place, so nobody moves on to another venue in the middle of the night."),
            ("Small weddings", "Up to fifty guests, the ceremony in the courtyard and the photographs taken without leaving the gate."),
            ("Companies and teams", "Away-days and anniversaries far enough from the office to feel like a change, and still an hour from Belgrade."),
        ],
        "kako_h": "How it works in practice",
        "kako": [
            ("The space", "Grass and paved terrace outside, a hall under a brick vault if it rains. You need not choose in advance or keep a fallback plan."),
            ("The table", "Up to fifty seats. The round tables, white linen and white chairs are ours, so you are not hiring them separately."),
            ("Decoration", "We work with decorators nearby and we welcome yours. Balloon arches, flowers and lighting all come through the gate without trouble."),
            ("Music", "Stage and sound go up in the courtyard. The wall around it means nobody bangs on it at eleven."),
            ("Parking", "Free, in front of the gate, and enough for the whole party."),
        ],
        "napomena_h": "Dates",
        "napomena_p": "Weekends in season go early and some go a year ahead. Send a date and a number of guests and we tell you the same day whether it is free.",
    },
    "trpeza": {
        "title": "The table and the cellar · Srem home cooking, Vrdnik",
        "desc": "Home cooking agreed in advance, around the number of guests and the occasion, with a wine cellar beneath the house.",
        "h1": "The table",
        "uvod": "You are not choosing off a card and not waiting for things to arrive. We settle it before you come, so the table is ready when you sit down.",
        "kuhinja_h": "The kitchen",
        "kuhinja_p": "Srem cooking, domestic, no airs. The ingredients come from here and the quantities are such that nobody leaves hungry. If someone does not eat meat or cannot have gluten, say so in advance and it is handled without a conversation at the table.",
        "jela": [
            ("Fruškogorski fruštuk", "The morning table for guests who stay over. Eggs, local cheese, kajmak, bacon, bread and apricot juice, so the day does not start with a drive to a bakery. (Fruštuk is the Srem word for breakfast, borrowed from the German Frühstück.)"),
            ("Soup and čorba", "Home-made, cooked that morning for that day."),
            ("From the grill", "Meat grilled out in the courtyard, with sides and salads from the garden, so the smell carries across the whole place."),
            ("Cake", "Home-made, to finish. And to take with you, if any survives."),
        ],
        "jela_napomena": "We put the menu together around the number of guests and the occasion. Tell us who you are bringing and what they like, and leave the rest to us.",
        "podrum_h": "The cellar",
        "podrum_p": "There is a wine cellar under the house, so a tasting means walking downstairs rather than driving anywhere. Fruška gora is wine country, the wineries are minutes away and several are in Vrdnik itself.",
        "radno_h": "Opening",
        "radno_p": "Open every day. For groups and celebrations the kitchen works by arrangement, so call before you come and your table will be ready.",
    },
    "fruska": {
        "title": "Fruška gora and Vrdnik · what to see from the kućerak",
        "desc": "A national park, eighteen monasteries, wineries and a thermal spa, all minutes from the kućerak in Vrdnik.",
        "h1": "Fruška gora",
        "uvod": "Vrdnik is the last village before the national park, which puts nature on the doorstep rather than an hour down the road.",
        "natpis": "Around us",
        "mesta_h": "Within reach",
        "mesta": [
            ("Fruška gora National Park", "Beech and lime forest, marked trails and viewpoints. The entrance is just above the village, so the woods are a ten minute walk away."),
            ("The monasteries", "Eighteen on the hills, eight in the Irig municipality. Staro and Novo Hopovo, Velika and Mala Remeta, Ravanica, Grgeteg, Jazak and Krušedol, all within half an hour's drive."),
            ("Wineries", "The Fruška gora wine route. Several wineries work in Vrdnik itself, a few minutes on foot, so a tasting need not be planned like an outing."),
            ("Vrdnik tower", "The remains of a medieval fort above the village. The climb is short and the view runs across the whole of Srem."),
            ("Vrdnik spa", "A thermal spring at thirty-two degrees and the spa pools, in the village itself."),
            ("On foot and by bike", "The trails start in Vrdnik. Bicycles and horse riding can be arranged, so there is nothing to bring with you."),
        ],
        "put_h": "Getting here",
        "put": [
            ("Novi Sad", "23 km"),
            ("Belgrade", "70 km"),
            ("Ruma", "15 km"),
            ("Nikola Tesla Airport", "52 km"),
        ],
        "put_p": "Belgrade is an hour away and Novi Sad twenty minutes. That is why people come here both for a single lunch and for a whole weekend.",
    },
    "kontakt": {
        "title": "Contact and booking · Ilkićev kućerak, Vrdnik",
        "desc": "Find out whether your date is free. Phone +381 65 288 0781, Mirka Laćarca 9, Vrdnik, Serbia.",
        "h1": "Contact",
        "uvod": "The phone is fastest, and one of us answers rather than a switchboard. If writing suits you better, use the form and we reply the same day.",
        "forma_h": "Send an enquiry",
        "forma_p": "Tell us the date, how many of you there are and the occasion. We come back on whether it is free and what we can put on, and settle the rest by phone.",
        "polja": {
            "ime": "Name", "email": "Email", "telefon": "Phone",
            "povod": "Occasion", "datum": "Date", "gosti": "Number of guests",
            "poruka": "Message",
            "povod_opcije": ["A stay in an apartment", "A celebration", "Lunch or dinner", "Something else"],
            "poruka_ph": "What are you planning, how many of you are there, and what matters to you?",
            "posalji": "Send enquiry",
        },
        "poruke": {
            "obavezno": "This field is required.",
            "nevalidno": "Please check this entry.",
            "salje": "Sending…",
            "posalji": "Send enquiry",
            "uspeh": "Thank you, your enquiry has arrived. We answer the same day.",
            "neuspeh": "That did not send. Please call +381 65 288 0781 or write to ilkic@kucerak-u-sremu.rs.",
        },
        "podaci_h": "Details",
        "adresa_l": "Address", "telefon_l": "Phone", "epasta_l": "Email",
        "radno_l": "Open", "radno_v": "Every day",
        "mapa_l": "Open in Google Maps",
    },
}

# ============================================================== DEUTSCH

DE = {
    "code": "de",
    "htmllang": "de",
    "ime": "Deutsch",
    "nav": {
        "pocetna": "Startseite", "kuce": "Häuser", "kuca2": "Zweizimmerhaus",
        "kuca1": "Einzimmerhaus", "restoran": "Restaurant",
        "imanje": "Das Anwesen", "apartmani": "Apartments",
        "bazen": "Der Pool", "galerija": "Galerie", "proslave": "Feiern",
        "trpeza": "Die Tafel", "fruska": "Fruška gora", "kontakt": "Kontakt",
    },
    "c": {
        "mesto": "Vrdnik · Fruška gora",
        "upit": "Anfrage senden",
        "pozovite": "Rufen Sie an",
        "poziv_natpis": "Reservierung",
        "sve_slike": "Zur Galerie",
        "nazad": "Zurück zum Anwesen",
        "preskoci": "Zum Inhalt springen",
        "meni": "Menü",
        "jezik": "Sprache",
        "prava": "Alle Rechte vorbehalten.",
        "izrada": "Gestaltung und Umsetzung",
        "pratite": "Folgen",
        "poseta": "Besuch",
        "kuca": "Das Haus",
        "ponuda": "Angebot",
        "okolina": "Umgebung",
        "poziv_h": "Erfahren Sie, ob Ihr Termin frei ist",
        "poziv_p": "Schicken Sie uns Datum und Gästezahl. Wir antworten am selben Tag, mit allem, was Sie vor Ihrer Entscheidung wissen müssen.",
    },
    "home": {
        "title": "Ilkićev kućerak · ein privates Anwesen in Vrdnik, Fruška gora",
        "desc": "Unterkunft in einem restaurierten Haus in Vrdnik, ein Restaurant mit Hausmannskost und ein Salzwasserpool. Das ganze Anwesen wird immer nur an eine Gesellschaft vergeben, vierzig Minuten von Novi Sad.",
        "h1": ["Übernachtung, Küche", "und Weinkeller", "an einem Ort"],
        "uvod": "Unterkunft in einem restaurierten Haus aus dem Srem, ein Restaurant mit Hausmannskost und ein Salzwasserpool. In Vrdnik, vierzig Minuten von Novi Sad. Für Familienurlaub, ein Wochenende zu zweit oder einen ruhigen Aufenthalt in der Natur der Fruška gora.",
        "stubovi": [
            ("apartmani", "Übernachten", "Bleiben Sie eine Nacht oder drei. Keine Rezeption, kein Flur, niemand hinter der Wand."),
            ("proslave", "Feiern", "Taufe, Geburtstag oder Hochzeit im kleinen Kreis, an einem Ort, den Sie an diesem Tag mit niemandem teilen."),
            ("trpeza", "Essen", "Hausgemachte Küche, abgestimmt darauf, wer kommt und was er mag."),
        ],
        "odlike": [
            ("sapa", "Haustiere willkommen", "Der Hund reist mit, Sie brauchen keine Betreuung"),
            ("kapija", "Völlige Privatsphäre", "An diesem Tag kommt nur Ihre Gesellschaft durchs Tor"),
            ("put", "40 Minuten von Novi Sad", "Nah genug für Hinfahrt und Rückfahrt am selben Tag"),
            ("vrt", "Garten mit 900 m²", "Platz für Kinder, Grill und eine lange Tafel im Schatten"),
            ("parking", "Kostenloser Parkplatz", "Vor dem Tor, genug für die ganze Gesellschaft"),
        ],
        "ukratko_natpis": "Kurz gefasst",
        "ukratko_h": "Ein sremisches Haus aus dem 19. Jahrhundert, mit dem ganzen Anwesen dazu",
        "ukratko_p1": "Der kućerak ist ein restauriertes sremisches Haus mitten in Vrdnik, mit gemauertem Ofen, Holzbalken und einem Weinkeller darunter. Vergeben wird das ganze Anwesen, und immer nur an eine Gesellschaft.",
        "ukratko_p2": "Draußen erwarten Sie ein weiter Hof, ein Walnussbaum, der den Pool beschattet, und ein Grill, der läuft, wann immer Sie ihn brauchen.",
        "ukratko_p3": "Die Bewertung auf Google liegt bei 4,7 von 5, aus mehr als 300 Rückmeldungen.",
        "kuca_natpis": "Privatsphäre",
        "kuca_h": "An diesem Tag sind Sie die einzigen Gäste",
        "kuca_p1": "Der kućerak wird nicht geteilt. An diesem Tag gehören Hof, Pool, Speiseraum und Keller allein Ihnen. Sie stören niemanden, niemand stört Sie, und Sie müssen sich nach nichts richten.",
        "restoran_natpis": "Restaurant",
        "restoran_h": "Das Menü nach Ihrer Wahl",
        "restoran_p": "Die Gäste wählen das Menü gemeinsam mit uns, damit alles auf Sie abgestimmt ist.",
        "dvoriste_natpis": "Der Hof",
        "dvoriste_h": "Der ganze Tag passt in dreißig Schritte",
        "dvoriste_p": "Vom Tor zur Wiese, zum Pool und in den Speiseraum unter dem Ziegelgewölbe. Alles liegt so nah beieinander, dass die Gesellschaft nicht auseinanderfällt und niemand irgendwohin fahren muss.",
        "ponuda_natpis": "Weshalb Leute kommen",
        "ponuda_h": "Die drei Gründe, die wir am häufigsten hören",
        "ponuda": [
            ("apartmani", "Um für ein, zwei Tage abzuschalten",
             "Zwei Apartments, siebzig Quadratmeter im größeren, zwei Schlafzimmer und ein Kamin. Sie kommen am Freitagabend und müssen bis Sonntag nirgendwohin.",
             "interior-apartment"),
            ("proslave", "Um im eigenen Kreis zu feiern",
             "Fünfzig Plätze an der Tafel, ein Hof für die Trauung und ein Pool für die Kinder. Alles an einem Ort, also zieht die Gesellschaft nicht um und der Abend reißt nicht ab.",
             "celebrations-tall"),
            ("trpeza", "Damit alle an einem Tisch sitzen",
             "Wir kochen für Ihre Gesellschaft, nicht nach Karte. Sagen Sie uns, wer kommt und was er mag, und die Tafel steht gedeckt zur vereinbarten Stunde.",
             "table-setting"),
        ],
        "bazen_natpis": "Wasser",
        "bazen_h": "Baden auch dann, wenn es draußen kalt ist",
        "bazen_p": "Vrdnik ist ein Kurort, und man kommt wegen des Wassers und der Luft hierher, nicht nur im Sommer. Unser Pool im Hof ist beheizt und mit Salzwasser gefüllt, also bleibt er lange nach dem Saisonende nutzbar. Eine Kaskade am einen Ende, Liegen im Schatten, und an diesem Tag gehört er Ihrer Gesellschaft.",
        "utisci_natpis": "Gäste",
        "citat": "Der Gastgeber und seine Frau sind ausgesprochen freundlich. Zur Begrüßung gab es Kaffee und selbstgemachten Saft.",
        "citat_izvor": "Ein Gast · Google, 4,7 von 5 (mehr als 300 Bewertungen)",
        "fruska_natpis": "Umgebung",
        "fruska_h": "Die Natur vor der Tür, nicht eine Autostunde entfernt",
        "fruska_p": "Vrdnik ist der letzte Ort vor dem Nationalpark, der Weg beginnt also, sobald Sie den Hof verlassen. Ein Morgenspaziergang ohne Planung, Klöster und Weingüter nach dem Frühstück, rechtzeitig zurück zum Mittagessen. Novi Sad liegt dreiundzwanzig Kilometer entfernt, Belgrad siebzig, das Wochenende vergeht also ohne lange Fahrten.",
        "fruska_cta": "Was man von Vrdnik aus sieht",
    },
    # VORLAEUFIG: Text des Kunden steht noch aus.
    "kuce": {
        "title": "Häuser · Ilkićev kućerak, Vrdnik",
        "desc": "Zwei Häuser in einem Hof in Vrdnik. Ein Zweizimmerhaus und ein Einzimmerhaus mit zwei Betten, beide mit eigener Küche und eigenem Bad.",
        "h1": "Häuser",
        "uvod": "Zwei Häuser im selben Hof. Sie werden zusammen genommen, wenn die Gesellschaft größer ist, oder jedes für sich.",
        "izbor_h": "Zwei Häuser, ein Hof",
        "k2_h": "Zweizimmerhaus",
        "k2_p": "Zwei Schlafzimmer, ein Doppelbett im einen und zwei Einzelbetten im anderen, mit eigenem Bad und voll ausgestatteter Küche.",
        "k1_h": "Einzimmerhaus",
        "k1_p": "Ein Raum mit zwei Betten, dazu eine voll ausgestattete Küche und ein Bad.",
        "napomena_h": "Zusammen oder einzeln",
        "napomena_p": "Das Anwesen wird immer nur an eine Gesellschaft vergeben, Hof, Pool und Keller gehören also in beiden Fällen Ihnen. Sagen Sie uns, wie viele Sie sind, und wir finden die Aufteilung.",
    },

    "kuca1": {
        "title": "Einzimmerhaus · Ilkićev kućerak, Vrdnik",
        "desc": "Einzimmerhaus in Vrdnik mit zwei Betten, voll ausgestatteter Küche und Bad.",
        "h1": "Einzimmerhaus",
        "uvod": "Für zwei, die übernachten, mit eigener Küche und eigenem Bad.",
        "natpis": "Unterkunft",
        "a_h": "Zwei Betten, Küche und Bad",
        "a_p1": "Ein Raum mit zwei Betten, dazu eine voll ausgestattete Küche und ein Bad.",
        "a_p2": "Es wird allein genommen, wenn Sie zu zweit kommen, oder zusätzlich zum Zweizimmerhaus, wenn die Gesellschaft größer ist. Pool, Speiseraum und Keller stehen Ihnen genauso zur Verfügung wie den Gästen im größeren Haus.",
        "oznake": ["2 Betten", "Ausgestattete Küche", "Bad"],
        "napomena_h": "Für größere Gruppen",
        "napomena_p": "Beide Häuser werden zusammen genommen, so schläft die ganze Familie an einem Ort. Sagen Sie uns, wie viele Sie sind, und wir finden die Aufteilung.",
    },

    "kuca2": {
        "title": "Zweizimmerhaus · Ilkićev kućerak, Vrdnik",
        "desc": "Zweizimmerhaus in Vrdnik: zwei Schlafzimmer, voll ausgestattete Küche und eigenes Bad.",
        "h1": "Zweizimmerhaus",
        "uvod": "Für Gäste, die bleiben, mit eigener Küche und eigenem Bad.",
        "natpis": "Übernachten",
        "a_h": "Zwei Zimmer, Küche und Bad nur für Sie",
        "a_p1": "Zwei Schlafzimmer, ein Doppelbett im einen und zwei Einzelbetten im anderen. Das Haus hat ein eigenes Bad und eine voll ausgestattete Küche.",
        "a_p2": "Es gibt keine Rezeption und keine festen Zeiten, Ankunft und Abreise richten sich nach Ihrer Fahrt.",
        "oznake": ["2 Schlafzimmer", "Doppelbett + 2 Betten", "Ausgestattete Küche", "Bad"],
        "napomena_h": "Für größere Gruppen",
        "napomena_p": "Kommt eine größere Gesellschaft, wird das ganze Haus zusammen vergeben, dann schlafen alle an einem Ort. Sagen Sie uns, wie viele Sie sind, und wir finden die Aufteilung.",
    },
    "restoran": {
        "title": "Restaurant · hausgemachte Srem-Küche, Vrdnik",
        "desc": "Ein Restaurant unter Ziegelgewölbe mit fünfzig Plätzen, hausgemachter Srem-Küche und einem Weinkeller unter dem Haus.",
        "h1": "Restaurant",
        "uvod": "Wir kochen für eine Gesellschaft, nicht nach Karte. Was auf den Tisch kommt, wird vorher besprochen.",
        "natpis": "Die Tafel",
        "sala_h": "Fünfzig Plätze unter Ziegelgewölbe",
        "sala_p1": "Die ganze Familie sitzt an einer Tafel, statt sich auf Räume zu verteilen, und Regen kann den Tag nicht verderben. Bei gutem Wetter wird auch draußen im Hof gedeckt.",
        "sala_p2": "Die Küche ist Srem-Küche, hausgemacht, ohne Allüren. Die Zutaten kommen von hier, und die Mengen sind so, dass niemand hungrig aufsteht. Wenn jemand kein Fleisch isst oder kein Gluten verträgt, sagen Sie es vorher, dann ist es geregelt.",
        "podrum_h": "Ein Weinkeller unter dem Haus",
        "podrum_p": "Eine Verkostung heißt Treppe hinunter statt irgendwohin fahren. Die Fruška gora ist Weinland, die Weingüter sind Minuten entfernt und mehrere liegen in Vrdnik selbst.",
        "radno_h": "Öffnung",
        "radno_p": "Täglich geöffnet. Für Gruppen und Feiern arbeitet die Küche nach Absprache, rufen Sie also vorher an, dann steht Ihre Tafel bereit.",
    },
    "imanje": {
        "title": "Das Anwesen · Ilkićev kućerak, Vrdnik",
        "desc": "Was Sie mit der Buchung bekommen: ein Haus mit zwei Apartments, einen Hof mit beheiztem Pool, einen Saal für fünfzig und einen Weinkeller, alles für eine Gesellschaft.",
        "h1": "Das Anwesen",
        "uvod": "Alles, was ein Tag oder ein Wochenende braucht, liegt im selben Hof. Nichts, wozu man fahren, und niemand, mit dem man es zusätzlich abstimmen müsste.",
        "natpis": "Das Anwesen",
        "sta_h": "Was Sie mit der Buchung bekommen",
        "redovi": [
            ("Das Haus", "Ein ebenerdiges Srem-Haus mit Holzbalken und Ziegelgewölben. Groß genug für die ganze Gesellschaft, klein genug, dass alle einander hören."),
            ("Apartments", "Zwei Apartments für alle, die bleiben, sodass niemand in der Umgebung ein Bett suchen oder nach dem Essen nach Hause fahren muss."),
            ("Saal und Speiseraum", "Fünfzig Plätze unter Ziegelgewölbe. Die ganze Familie sitzt an einer Tafel, statt sich auf Räume zu verteilen, und Regen kann den Tag nicht verderben."),
            ("Keller", "Ein Weinkeller unter dem Haus, für eine Verkostung oder für den Teil des Abends, an dem sich die Gesellschaft ohnehin teilt."),
            ("Pool", "Beheizt, Salzwasser, mit Kaskade und Liegen. Die Kinder haben, wo sie den Tag verbringen, und niemand muss sie zum Baden fahren."),
            ("Hof", "Wiese, Lavendel und Rosen, Grill und Platz für Bühne und Dekoration, Trauung und Fest können also draußen stattfinden."),
            ("Parken", "Vor dem Tor und kostenlos, niemand dreht also Runden durch den Ort."),
        ],
        "detalji_h": "Gut zu wissen, bevor Sie buchen",
        "detalji": [
            ("Haustiere", "Können wir nicht aufnehmen. Tut uns leid, ist aber so."),
            ("Kinder", "In jedem Alter willkommen. Der Pool ist nicht eingezäunt, rechnen Sie bei den Kleinsten damit."),
            ("An- und Abreise", "Keine Rezeption, keine festen Zeiten. Wir richten uns nach Ihrer Anfahrt, niemand schaut also auf die Uhr."),
            ("WLAN und Parken", "WLAN kostenlos im ganzen Hof, geparkt wird vor dem Tor."),
            ("Zahlung", "Wird bei der Buchung vereinbart, ohne Nachträge."),
        ],
    },
    "apartmani": {
        "title": "Apartments · Ilkićev kućerak, Vrdnik",
        "desc": "Zwei Apartments im kućerak in Vrdnik, für Gäste, die bleiben. Keine Rezeption, kein Flur, niemand hinter der Wand.",
        "h1": "Apartments",
        "uvod": "Für alle, die nach dem Abendessen nicht mehr fahren wollen oder das Wochenende verlängern möchten.",
        "a1_h": "Das größere Apartment",
        "a1_p": "Siebzig Quadratmeter und zwei Schlafzimmer, ein Doppelbett im einen, zwei Betten im anderen. Es hat eigene Küche und eigenes Bad, Sie sind also von niemandem abhängig, und Kamin und Terrasse zu den Bergen hin sind der Grund, warum Gäste auch bei Kälte bleiben.",
        "a1_oznake": ["70 m²", "2 Schlafzimmer", "Doppelbett + 2 Betten", "Küche", "Kamin", "Terrasse", "Bergblick", "Klimaanlage"],
        "a2_h": "Das kleinere Apartment",
        "a2_p": "Für zwei, im selben Haus und im selben Hof. Pool, Speiseraum und Keller stehen Ihnen genauso offen wie den Gästen des größeren Apartments.",
        "a2_oznake": ["Für zwei", "Bad", "Klimaanlage", "Zugang zum Hof", "Pool"],
        "napomena": "Für größere Gruppen wird das ganze Haus zusammen vergeben, dann schläft die ganze Familie an einem Ort. Sagen Sie uns, wie viele Sie sind, und wir finden die Aufteilung.",
    },
    "bazen": {
        "title": "Der Pool · Ilkićev kućerak, Vrdnik",
        "desc": "Der Pool im Hof in Vrdnik, mit Whirlpool, Heizung und Salzwasser.",
        "h1": "Der Pool",
        "uvod": "Ein Pool mit Whirlpool, Heizung und Salzwasser, ganz nach Ihrem Wunsch.",
        "voda_h": "Beheizt oder mit Salzwasser, ganz nach Wunsch",
        "voda_p1": "Ein Pool mit Whirlpool, Heizung und Salzwasser, ganz nach Ihrem Wunsch.",
        "voda_p2": "Unser Pool ist beheizt und mit Salzwasser gefüllt. Salz reizt Augen und Haut weniger als Chlor, Kinder halten es also deutlich länger darin aus, und die Badesaison dauert spürbar länger als bei einem gewöhnlichen Pool. Kaskade am einen Ende, Liegen im Schatten.",
        "oznake": ["Whirlpool", "Heizung", "Salzwasser"],
        "noc_h": "Der Abend muss nicht enden",
        "noc_p": "Abends gehen die Lichter im Wasser und unter den Bögen an und der Hof läuft bis spät. Ringsum verläuft eine Mauer, es gibt also keinen Nachbarn, für den man die Musik leiser drehen müsste.",
    },
    "galerija": {
        "title": "Galerie · Ilkićev kućerak, Vrdnik",
        "desc": "Wie der kućerak in Vrdnik wirklich aussieht: der Hof bei Tag und bei Nacht, der Pool, die Bögen, die Apartments und eine gedeckte Tafel.",
        "h1": "Galerie",
        "uvod": "Damit Sie sehen, wohin Sie kommen, bevor Sie sich entscheiden.",
    },
    "proslave": {
        "title": "Feiern · privater Hof und Saal in Vrdnik",
        "desc": "Eine private Location für Feiern in Vrdnik. Fünfzig Plätze an der Tafel, Hof, Pool und ein Saal unter Gewölbe, alles für eine Gesellschaft und ohne Sperrstunde.",
        "h1": "Feiern",
        "uvod": "",
        "sta_h": "Was hier gefeiert wird",
        "dogovor_p": "Absprachen treffen wir telefonisch, und wir übernehmen jede der hier genannten Feiern.",
        "sta": [
            ("Taufen und Slava", "Ein Familienessen unter den Bögen oder draußen im Hof. Die Küche wird vorher abgestimmt, der Gastgeber verbringt den Tag also an der Tafel und nicht in der Küche."),
            ("Geburtstage", "Von Kindergeburtstagen, bei denen Wiese und Pool zur Verfügung stehen, bis zu runden mit langer Tafel und Musik bis spät."),
            ("Abibälle", "Tische, Stühle, Dekoration und Pool an einem Ort, niemand zieht also mitten in der Nacht weiter."),
            ("Kleine Hochzeiten", "Bis zu fünfzig Gäste, die Trauung im Hof und Fotos, ohne das Tor zu verlassen."),
            ("Firmen und Teams", "Team-Tage und Jubiläen weit genug vom Büro, um nach Abwechslung zu fühlen, und trotzdem eine Stunde von Belgrad."),
        ],
        "kako_h": "Wie es in der Praxis abläuft",
        "kako": [
            ("Der Raum", "Wiese und gepflasterte Terrasse draußen, ein Saal unter Ziegelgewölbe, falls es regnet. Sie müssen sich nicht vorher entscheiden und keinen Ersatzplan bereithalten."),
            ("Die Tafel", "Bis zu fünfzig Plätze. Runde Tische, weiße Wäsche und weiße Stühle stellen wir, Sie mieten sie also nicht zusätzlich."),
            ("Dekoration", "Wir arbeiten mit Dekorateuren aus der Gegend und empfangen auch Ihre. Ballonbögen, Blumen und Licht passen ohne Weiteres durch das Tor."),
            ("Musik", "Bühne und Anlage kommen in den Hof. Die Mauer ringsum bedeutet, dass um elf niemand dagegen klopft."),
            ("Parken", "Kostenlos, vor dem Tor, und genug für die ganze Gesellschaft."),
        ],
        "napomena_h": "Termine",
        "napomena_p": "Wochenenden in der Saison sind früh weg, manche ein Jahr im Voraus. Schicken Sie Datum und Gästezahl, und wir sagen Ihnen noch am selben Tag, ob frei ist.",
    },
    "trpeza": {
        "title": "Tafel und Keller · hausgemachte Srem-Küche, Vrdnik",
        "desc": "Hausgemachte Küche, vorher abgestimmt auf Gästezahl und Anlass, dazu ein Weinkeller unter dem Haus.",
        "h1": "Die Tafel",
        "uvod": "Sie wählen nicht nach Karte und warten nicht darauf, dass etwas kommt. Wir klären es, bevor Sie da sind, die Tafel steht also bereit, wenn Sie sich setzen.",
        "kuhinja_h": "Die Küche",
        "kuhinja_p": "Srem-Küche, hausgemacht, ohne Allüren. Die Zutaten kommen von hier, und die Mengen sind so, dass niemand hungrig aufsteht. Wenn jemand kein Fleisch isst oder kein Gluten verträgt, sagen Sie es vorher, dann ist es geregelt, ohne dass am Tisch darüber geredet werden muss.",
        "jela": [
            ("Fruškogorski fruštuk", "Der Morgentisch für Gäste, die bleiben. Eier, Käse aus der Gegend, Kajmak, Speck, Brot und Aprikosensaft, damit der Tag nicht mit einer Fahrt zum Bäcker beginnt. (Fruštuk ist das Srem-Wort für Frühstück, entlehnt aus dem Deutschen.)"),
            ("Suppe und Čorba", "Hausgemacht, an diesem Morgen für diesen Tag gekocht."),
            ("Vom Grill", "Das Fleisch wird draußen im Hof gegrillt, dazu Beilagen und Salate aus dem Garten, der Duft zieht also über den ganzen Hof."),
            ("Kuchen", "Hausgemacht, zum Abschluss. Und zum Mitnehmen, falls etwas übrig bleibt."),
        ],
        "jela_napomena": "Wir stellen das Menü nach Gästezahl und Anlass zusammen. Sagen Sie uns, wen Sie mitbringen und was er mag, den Rest überlassen Sie uns.",
        "podrum_h": "Der Keller",
        "podrum_p": "Unter dem Haus liegt ein Weinkeller, eine Verkostung heißt also Treppe hinunter statt irgendwohin fahren. Die Fruška gora ist Weinland, die Weingüter sind Minuten entfernt und mehrere liegen in Vrdnik selbst.",
        "radno_h": "Öffnung",
        "radno_p": "Täglich geöffnet. Für Gruppen und Feiern arbeitet die Küche nach Absprache, rufen Sie also vorher an, dann steht Ihre Tafel bereit.",
    },
    "fruska": {
        "title": "Fruška gora und Vrdnik · was man vom kućerak aus sieht",
        "desc": "Ein Nationalpark, achtzehn Klöster, Weingüter und ein Thermalbad, alles wenige Minuten vom kućerak in Vrdnik.",
        "h1": "Fruška gora",
        "uvod": "Vrdnik ist der letzte Ort vor dem Nationalpark, damit liegt die Natur vor der Tür und nicht eine Autostunde entfernt.",
        "natpis": "Umgebung",
        "mesta_h": "In Reichweite",
        "mesta": [
            ("Nationalpark Fruška gora", "Buchen- und Lindenwald, markierte Wege und Aussichtspunkte. Der Eingang liegt direkt oberhalb des Ortes, der Wald ist also zehn Gehminuten entfernt."),
            ("Die Klöster", "Achtzehn auf den Bergen, acht in der Gemeinde Irig. Staro und Novo Hopovo, Velika und Mala Remeta, Ravanica, Grgeteg, Jazak und Krušedol, alle in einer halben Autostunde."),
            ("Weingüter", "Die Weinstraße der Fruška gora. Mehrere Weingüter arbeiten in Vrdnik selbst, wenige Gehminuten entfernt, eine Verkostung muss also nicht wie ein Ausflug geplant werden."),
            ("Turm von Vrdnik", "Die Reste einer mittelalterlichen Festung über dem Ort. Der Aufstieg ist kurz, der Blick geht über den ganzen Srem."),
            ("Thermalbad Vrdnik", "Eine Thermalquelle mit zweiunddreißig Grad und die Kurbecken, im Ort selbst."),
            ("Zu Fuß und mit dem Rad", "Die Wege beginnen in Vrdnik. Fahrräder und Ausritte vermitteln wir, Sie müssen also nichts mitbringen."),
        ],
        "put_h": "Anfahrt",
        "put": [
            ("Novi Sad", "23 km"),
            ("Belgrad", "70 km"),
            ("Ruma", "15 km"),
            ("Flughafen Nikola Tesla", "52 km"),
        ],
        "put_p": "Belgrad ist eine Autostunde entfernt, Novi Sad zwanzig Minuten. Deshalb kommen hierher sowohl die, die nur zum Mittagessen bleiben, als auch die, die ein ganzes Wochenende bleiben.",
    },
    "kontakt": {
        "title": "Kontakt und Reservierung · Ilkićev kućerak, Vrdnik",
        "desc": "Erfahren Sie, ob Ihr Termin frei ist. Telefon +381 65 288 0781, Mirka Laćarca 9, Vrdnik, Serbien.",
        "h1": "Kontakt",
        "uvod": "Am schnellsten geht es telefonisch, und es meldet sich einer von uns statt einer Zentrale. Wenn Ihnen Schreiben lieber ist, nutzen Sie das Formular, wir antworten am selben Tag.",
        "forma_h": "Anfrage senden",
        "forma_p": "Nennen Sie Datum, Personenzahl und Anlass. Wir melden uns, ob frei ist und was wir vorbereiten können, den Rest klären wir am Telefon.",
        "polja": {
            "ime": "Name", "email": "E-Mail", "telefon": "Telefon",
            "povod": "Anlass", "datum": "Datum", "gosti": "Anzahl der Gäste",
            "poruka": "Nachricht",
            "povod_opcije": ["Aufenthalt im Apartment", "Eine Feier", "Mittag- oder Abendessen", "Etwas anderes"],
            "poruka_ph": "Was planen Sie, wie viele sind Sie, und worauf kommt es Ihnen an?",
            "posalji": "Anfrage senden",
        },
        "poruke": {
            "obavezno": "Dieses Feld ist erforderlich.",
            "nevalidno": "Bitte prüfen Sie die Eingabe.",
            "salje": "Wird gesendet…",
            "posalji": "Anfrage senden",
            "uspeh": "Danke, Ihre Anfrage ist angekommen. Wir antworten am selben Tag.",
            "neuspeh": "Das Senden hat nicht geklappt. Bitte rufen Sie +381 65 288 0781 an oder schreiben Sie an ilkic@kucerak-u-sremu.rs.",
        },
        "podaci_h": "Angaben",
        "adresa_l": "Adresse", "telefon_l": "Telefon", "epasta_l": "E-Mail",
        "radno_l": "Geöffnet", "radno_v": "Täglich",
        "mapa_l": "In Google Maps öffnen",
    },
}

JEZICI = {"sr": SR, "en": EN, "de": DE}
